### ISSUE TITLE
Setup Prometheus Monitoring with Docker Compose

### ISSUE THREAD

**Issue by Rurutia1027** [Rurutia1027/HQL-Fabric#16]
## Description 
In this task, we aim to integrate Prometheus into our local development using Docker Compose. This allows us to test and validate metric collection for `hql-fabric-example` app before deploying it to Kubernetes. 

## Tasks 
- Add a standalone `prometheus.yml` configuration file under `hql-fabric-monitor/src/main/resources`.
- Use Docker Compose to run both `hql-fabric-example` and a Prometheus container.
- Configure Prometheus to scrape metrics from `hql-fabric-example`.
- Verify Prometheus dashboard is accessible at `http://localhost:9090`.
- Confirm metrics endpoint (e.g., /actuator/prometheus) from `hql-fabric-example` is being scraped. 

## Resources 
- Prometheus base image: prom/prometheus
- Sample Prometheus config:

```yaml 
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hql-fabric-example'
    static_configs:
      - targets: ['host.docker.internal:8080']
```
