### ISSUE TITLE
Add Pluggable ShardRouter and HQL Query Sharding Support

### ISSUE THREAD

**Issue by Rurutia1027** [Rurutia1027/HQL-Fabric#21]
## User Story 
```
As a developer using the hql-fabric framework, I want to enable optional sharding behavior by including 
- hql-fabric-core 
- hql-fabric-sharding 

in my project. 

So that my IHqlQueryService calls can automatically route to the correct database instance based on dynamic sharding rules like user ID, region, time, etc. 
```

## Acceptance Criteria

- A new `ShardRouter` interface is defined to abstract routing strategy.
- Built-in `ShardRouter` implementations are provided: 
- 1. HashModeShardRouter (this is the default Router)
- 2. TimeShardRouter (month-based or quater-based routing)
- 3. TagBasedShardRouter (region/tenant routing)
- 4. RangeShardRouter (static ranges, e.g., 0-9999 -> shard_0) 

- `ShardContextHolder` this provides context info like shard based on which column, table, and tenantTag, partitionKey, or which router adopted. 
- `ShardingHqlQueryService` this extends `IHqlQueryService` defined in module of `hql-fabric-core` and it overrides `IHqlQueryService`'s inner defined functions and implemented them via sharding logic 
- The routing result determines which `SessionFactory` is used for execution. 
- If `hql-fabric-sharding` is not present or sharding is disabled, the system falls back to the default `HqlQueryService`.

- `application.yml` for hql-fabric-sharding shown below: 

```yml 
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      jdbc:
        batch-size: 0
      cache:
        provider-class: org.hibernate.cache.internal.StandardQueryCache
      default-schema: ""

sql:
  fabric:
    sharding:
      enabled: true
      shard-count: 3
      strategy: hash # this supports hash, range, time, tag
      datasources:
        shard0:
          url: jdbc:postgresql://localhost:5432/hql_fabric_db_0
          username: admin
          password: admin
          driver-class-name: org.postgresql.Driver
        shard1:
          url: jdbc:postgresql://localhost:5432/hql_fabric_db_1
          username: admin
          password: admin
          driver-class-name: org.postgresql.Driver
        shard2:
          url: jdbc:postgresql://localhost:5432/hql_fabric_db_2
          username: admin
          password: admin
          driver-class-name: org.postgresql.Driver
```

## Tech Tasks 

- Define `ShardRouter` interface
- Implement `HashModShardRouter`, `RangeShardRouter`, etc. 
- Define and implement `ShardContextHolder`
- Implement `ShardingHqlQueryService`
- Use Spring `@ConditionalOnClass` or `@ConditionalOnProperty` to write the correct service
- Write unit tests for each routing strategy 
- Add documentation and usage examples

## Notes
- The architecture is desigend to be pluggable. New routing strategies can be registered via Spring without touching the core service logic.
- A project with `hql-fabric-core` only runs in non-shared (single DB) mode by default.
- A project with `hql-fabric-core` + `hql-fabric-sharding` and enable sharding uses `ShardingHqlQueryService`.
